Accounted for edge cases with SVMClassifier
TimAdamson21/gpslog pull request #3
Opened 2017-11-14 01:21 UTC by Ramenoodlez

Made sure that it creates the right number of tracks per segment.

2017-11-14 18:16 UTC, TimAdamson21 commented on GPSlog_Basic/app/src/main/java/com/example/gpslog/SVMClassifier.java
> +            else if (isSegment == true && tracks.get(i).hiddenState != HMMClassifier.FREEFLOW) {
Boolean Zen. It can just be else if (isSegment && ...) because isSegment is in and of itself a boolean. This is also true above and below.

2017-11-14 18:25 UTC, TimAdamson21 requested changes
I don't know if you did this already, but I would suggest walking/busing/driving around and collecting some data on your phone, and then testing the segmentation in debug mode to make sure it is working.  Aside from that, there are the two suggestions I made, and I think otherwise it looks pretty good.

2017-11-14 18:25 UTC, TimAdamson21 commented on GPSlog_Basic/app/src/main/java/com/example/gpslog/SVMClassifier.java
> +        for(int i = 0; i <= tracks.size(); i++){
If I am correct, this for loop will go out of bounds when i == tracks.size() and it will throw an OutOfBoundsException.

2017-11-14 18:33 UTC, Ramenoodlez commented
See recent changes to the commit, both of your recommendations were spot on. I will take it out for a swing right now.

2017-11-14 18:35 UTC, TimAdamson21 approved these changes

2017-11-14 18:37 UTC, TimAdamson21 commented
As soon as you have tested the code with some data we can go ahead and merge. Great job!

2017-11-22 21:45 UTC, Ramenoodlez commented
I tested this and made one small tweak in the SVMClassifier class to handle the last track in each segment. See the more recent commit to zack-changes for the updated code, along with the changes to the Segment class.

2017-11-24 05:22 UTC, closed without merging